<?php

namespace Database\Seeders\p15_asistencia;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BiometricosSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('p15_biometricos')->delete();
        
        \DB::table('p15_biometricos')->insert(array (
            0 => 
            array (
                'biometrico_id' => 64,
                'nombre' => '10.0.135.123',
                'acceso' => NULL,
                'ip' => '10.0.135.123',
                'tipo' => 'DACTILAR',
                'ubicacion' => '',
                'activo' => true,
                'created_at' => '2024-04-19 18:02:46',
                'updated_at' => '2024-04-19 18:02:46',
            ),
            1 => 
            array (
                'biometrico_id' => 65,
                'nombre' => '10.0.250.97',
                'acceso' => NULL,
                'ip' => '10.0.250.97',
                'tipo' => 'DACTILAR',
                'ubicacion' => '',
                'activo' => true,
                'created_at' => '2024-04-19 18:02:46',
                'updated_at' => '2024-04-19 18:02:46',
            ),
            2 => 
            array (
                'biometrico_id' => 66,
                'nombre' => '10.1.150.193',
                'acceso' => NULL,
                'ip' => '10.1.150.193',
                'tipo' => 'DACTILAR',
                'ubicacion' => '',
                'activo' => true,
                'created_at' => '2024-04-19 18:02:46',
                'updated_at' => '2024-04-19 18:02:46',
            ),
            3 => 
            array (
                'biometrico_id' => 67,
                'nombre' => '10.1.150.194',
                'acceso' => NULL,
                'ip' => '10.1.150.194',
                'tipo' => 'DACTILAR',
                'ubicacion' => '',
                'activo' => true,
                'created_at' => '2024-04-19 18:02:46',
                'updated_at' => '2024-04-19 18:02:46',
            ),
            4 => 
            array (
                'biometrico_id' => 68,
                'nombre' => '10.1.150.195',
                'acceso' => NULL,
                'ip' => '10.1.150.195',
                'tipo' => 'DACTILAR',
                'ubicacion' => '',
                'activo' => true,
                'created_at' => '2024-04-19 18:02:46',
                'updated_at' => '2024-04-19 18:02:46',
            ),
            5 => 
            array (
                'biometrico_id' => 69,
                'nombre' => '10.1.150.196',
                'acceso' => NULL,
                'ip' => '10.1.150.196',
                'tipo' => 'DACTILAR',
                'ubicacion' => '',
                'activo' => true,
                'created_at' => '2024-04-19 18:02:46',
                'updated_at' => '2024-04-19 18:02:46',
            ),
            6 => 
            array (
                'biometrico_id' => 70,
                'nombre' => '10.1.150.197',
                'acceso' => NULL,
                'ip' => '10.1.150.197',
                'tipo' => 'DACTILAR',
                'ubicacion' => '',
                'activo' => true,
                'created_at' => '2024-04-19 18:02:46',
                'updated_at' => '2024-04-19 18:02:46',
            ),
            7 => 
            array (
                'biometrico_id' => 71,
                'nombre' => '10.1.150.198',
                'acceso' => NULL,
                'ip' => '10.1.150.198',
                'tipo' => 'DACTILAR',
                'ubicacion' => '',
                'activo' => true,
                'created_at' => '2024-04-19 18:02:46',
                'updated_at' => '2024-04-19 18:02:46',
            ),
            8 => 
            array (
                'biometrico_id' => 72,
                'nombre' => '10.1.150.199',
                'acceso' => NULL,
                'ip' => '10.1.150.199',
                'tipo' => 'DACTILAR',
                'ubicacion' => '',
                'activo' => true,
                'created_at' => '2024-04-19 18:02:46',
                'updated_at' => '2024-04-19 18:02:46',
            ),
            9 => 
            array (
                'biometrico_id' => 73,
                'nombre' => '10.1.150.200',
                'acceso' => NULL,
                'ip' => '10.1.150.200',
                'tipo' => 'DACTILAR',
                'ubicacion' => '',
                'activo' => true,
                'created_at' => '2024-04-19 18:02:46',
                'updated_at' => '2024-04-19 18:02:46',
            ),
            10 => 
            array (
                'biometrico_id' => 74,
                'nombre' => '10.1.225.30',
                'acceso' => NULL,
                'ip' => '10.1.225.30',
                'tipo' => 'DACTILAR',
                'ubicacion' => '',
                'activo' => true,
                'created_at' => '2024-04-19 18:02:46',
                'updated_at' => '2024-04-19 18:02:46',
            ),
            11 => 
            array (
                'biometrico_id' => 75,
                'nombre' => '10.1.225.31',
                'acceso' => NULL,
                'ip' => '10.1.225.31',
                'tipo' => 'DACTILAR',
                'ubicacion' => '',
                'activo' => true,
                'created_at' => '2024-04-19 18:02:46',
                'updated_at' => '2024-04-19 18:02:46',
            ),
            12 => 
            array (
                'biometrico_id' => 76,
                'nombre' => '10.1.225.32',
                'acceso' => NULL,
                'ip' => '10.1.225.32',
                'tipo' => 'DACTILAR',
                'ubicacion' => '',
                'activo' => true,
                'created_at' => '2024-04-19 18:02:46',
                'updated_at' => '2024-04-19 18:02:46',
            ),
            13 => 
            array (
                'biometrico_id' => 77,
                'nombre' => '10.36.0.226',
                'acceso' => NULL,
                'ip' => '10.36.0.226',
                'tipo' => 'DACTILAR',
                'ubicacion' => '',
                'activo' => true,
                'created_at' => '2024-04-19 18:02:46',
                'updated_at' => '2024-04-19 18:02:46',
            ),
            14 => 
            array (
                'biometrico_id' => 1,
                'nombre' => 'ACCESO 1',
                'acceso' => NULL,
                'ip' => '10.1.17.92',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'ACCESO 1',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            15 => 
            array (
                'biometrico_id' => 2,
                'nombre' => 'ADMINISTRACIÓN FINANCIERA',
                'acceso' => NULL,
                'ip' => '10.1.17.82',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'ADMINISTRACIÓN FINANCIERA',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            16 => 
            array (
                'biometrico_id' => 3,
                'nombre' => 'ALMACÉN CENTRAL',
                'acceso' => NULL,
                'ip' => '10.1.135.125',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'ALMACÉN CENTRAL',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            17 => 
            array (
                'biometrico_id' => 4,
                'nombre' => 'AT_ACOXPA',
                'acceso' => NULL,
                'ip' => '10.1.143.65',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'AT_ACOXPA',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            18 => 
            array (
                'biometrico_id' => 5,
                'nombre' => 'AT_BENITO_JUAREZ',
                'acceso' => NULL,
                'ip' => '10.1.144.65',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'AT_BENITO_JUAREZ',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            19 => 
            array (
                'biometrico_id' => 6,
                'nombre' => 'AT_BOSQUES',
                'acceso' => NULL,
                'ip' => '10.1.138.97',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'AT_BOSQUES',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            20 => 
            array (
                'biometrico_id' => 7,
                'nombre' => 'AT_CUAJIMALPA',
                'acceso' => NULL,
                'ip' => '10.1.135.50',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'AT_CUAJIMALPA',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            21 => 
            array (
                'biometrico_id' => 8,
                'nombre' => 'AT_MEYEHUALCO',
                'acceso' => NULL,
                'ip' => '10.1.142.33',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'AT_MEYEHUALCO',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            22 => 
            array (
                'biometrico_id' => 9,
                'nombre' => 'AT_MILPA_ALTA',
                'acceso' => NULL,
                'ip' => '10.1.140.114',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'AT_MILPA_ALTA',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            23 => 
            array (
                'biometrico_id' => 10,
                'nombre' => 'AT_PARQUE_LIRA',
                'acceso' => NULL,
                'ip' => '10.1.133.50',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'AT_PARQUE_LIRA',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            24 => 
            array (
                'biometrico_id' => 11,
                'nombre' => 'AT_PERISUR',
                'acceso' => NULL,
                'ip' => '10.1.139.115',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'AT_PERISUR',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            25 => 
            array (
                'biometrico_id' => 12,
                'nombre' => 'AT_SAN_JERONIMO',
                'acceso' => NULL,
                'ip' => '10.1.139.50',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'AT_SAN_JERONIMO',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            26 => 
            array (
                'biometrico_id' => 13,
                'nombre' => 'AT_SAN_LAZARO 24214',
                'acceso' => NULL,
                'ip' => '10.1.151.41',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'AT_SAN_LAZARO 24214',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            27 => 
            array (
                'biometrico_id' => 14,
                'nombre' => 'AT_TAXQUEÑA',
                'acceso' => NULL,
                'ip' => '10.1.150.73',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'AT_TAXQUEÑA',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            28 => 
            array (
                'biometrico_id' => 15,
                'nombre' => 'AT_TEZONCO',
                'acceso' => NULL,
                'ip' => '10.1.137.129',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'AT_TEZONCO',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            29 => 
            array (
                'biometrico_id' => 16,
                'nombre' => 'AT_TEZONTLE',
                'acceso' => NULL,
                'ip' => '10.1.136.178',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'AT_TEZONTLE',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            30 => 
            array (
                'biometrico_id' => 17,
                'nombre' => 'AT_XOCHIMILCO',
                'acceso' => NULL,
                'ip' => '10.1.140.49',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'AT_XOCHIMILCO',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            31 => 
            array (
                'biometrico_id' => 18,
                'nombre' => 'CATASTRO',
                'acceso' => NULL,
                'ip' => '10.1.17.88',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'CATASTRO',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            32 => 
            array (
                'biometrico_id' => 19,
                'nombre' => 'CD_PERISUR',
                'acceso' => NULL,
                'ip' => '10.1.252.52',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'CD_PERISUR',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            33 => 
            array (
                'biometrico_id' => 20,
                'nombre' => 'CONTRALORIA INTERNA',
                'acceso' => NULL,
                'ip' => '10.1.17.83',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'CONTRALORIA INTERNA',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            34 => 
            array (
                'biometrico_id' => 21,
                'nombre' => 'CS_GRAN_SUR',
                'acceso' => NULL,
                'ip' => '10.1.104.40',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'CS_GRAN_SUR',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            35 => 
            array (
                'biometrico_id' => 22,
                'nombre' => 'CS_MIGUEL_ANGEL',
                'acceso' => NULL,
                'ip' => '10.1.98.161',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'CS_MIGUEL_ANGEL',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            36 => 
            array (
                'biometrico_id' => 23,
                'nombre' => 'CS_MIXCOAC',
                'acceso' => NULL,
                'ip' => '10.1.106.40',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'CS_MIXCOAC',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            37 => 
            array (
                'biometrico_id' => 24,
                'nombre' => 'CS_OLIVAR_DEL_PADRE',
                'acceso' => NULL,
                'ip' => '10.1.108.40',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'CS_OLIVAR_DEL_PADRE',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            38 => 
            array (
                'biometrico_id' => 25,
                'nombre' => 'CS_ROJO_GOMEZ',
                'acceso' => NULL,
                'ip' => '10.1.98.34',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'CS_ROJO_GOMEZ',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            39 => 
            array (
                'biometrico_id' => 26,
                'nombre' => 'CST_ASTURIAS',
                'acceso' => NULL,
                'ip' => '10.1.107.50',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'CST_ASTURIAS',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            40 => 
            array (
                'biometrico_id' => 27,
                'nombre' => 'CST_CUITLAHUAC 38766',
                'acceso' => NULL,
                'ip' => '10.1.97.40',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'CST_CUITLAHUAC 38766',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            41 => 
            array (
                'biometrico_id' => 28,
                'nombre' => 'CST_GALERIAS',
                'acceso' => NULL,
                'ip' => '10.1.109.40',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'CST_GALERIAS',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            42 => 
            array (
                'biometrico_id' => 29,
                'nombre' => 'CST_LA VILLA 38766',
                'acceso' => NULL,
                'ip' => '10.1.103.34',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'CST_LA VILLA 38766',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            43 => 
            array (
                'biometrico_id' => 30,
                'nombre' => 'CST_TLATELOLCO 38766',
                'acceso' => NULL,
                'ip' => '10.1.102.40',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'CST_TLATELOLCO 38766',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            44 => 
            array (
                'biometrico_id' => 31,
                'nombre' => 'DGA 2 PISO',
                'acceso' => NULL,
                'ip' => '10.1.17.89',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'DGA 2 PISO',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            45 => 
            array (
                'biometrico_id' => 32,
                'nombre' => 'DGI 1 SÓTANO',
                'acceso' => NULL,
                'ip' => '10.1.17.87',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'DGI 1 SÓTANO',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            46 => 
            array (
                'biometrico_id' => 33,
                'nombre' => 'DGI 2 SÓTANO',
                'acceso' => NULL,
                'ip' => '10.1.17.86',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'DGI 2 SÓTANO',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            47 => 
            array (
                'biometrico_id' => 34,
                'nombre' => 'DSG',
                'acceso' => NULL,
                'ip' => '10.1.17.85',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'DSG',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            48 => 
            array (
                'biometrico_id' => 35,
                'nombre' => 'GYM CAF',
                'acceso' => NULL,
                'ip' => '10.1.17.93',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'GYM CAF',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            49 => 
            array (
                'biometrico_id' => 36,
                'nombre' => 'IZA MZ 1',
                'acceso' => NULL,
                'ip' => '10.1.33.67',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'IZA MZ 1',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            50 => 
            array (
                'biometrico_id' => 37,
                'nombre' => 'IZA MZ 2',
                'acceso' => NULL,
                'ip' => '10.1.33.72',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'IZA MZ 2',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            51 => 
            array (
                'biometrico_id' => 38,
                'nombre' => 'IZA PB 1',
                'acceso' => NULL,
                'ip' => '10.1.33.65',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'IZA PB 1',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            52 => 
            array (
                'biometrico_id' => 39,
                'nombre' => 'IZA PB 2',
                'acceso' => NULL,
                'ip' => '10.1.33.66',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'IZA PB 2',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            53 => 
            array (
                'biometrico_id' => 40,
                'nombre' => 'IZA PISO 12',
                'acceso' => NULL,
                'ip' => '10.1.33.69',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'IZA PISO 12',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            54 => 
            array (
                'biometrico_id' => 41,
                'nombre' => 'IZA PISO 15',
                'acceso' => NULL,
                'ip' => '10.1.33.70',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'IZA PISO 15',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            55 => 
            array (
                'biometrico_id' => 42,
                'nombre' => 'IZA PISO 6',
                'acceso' => NULL,
                'ip' => '10.1.33.68',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'IZA PISO 6',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            56 => 
            array (
                'biometrico_id' => 43,
                'nombre' => 'OFICINA DEL SECRETARIO',
                'acceso' => NULL,
                'ip' => '10.1.17.75',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'OFICINA DEL SECRETARIO',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            57 => 
            array (
                'biometrico_id' => 44,
                'nombre' => 'POLÍTICA FISCAL',
                'acceso' => NULL,
                'ip' => '10.1.17.84',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'POLÍTICA FISCAL',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            58 => 
            array (
                'biometrico_id' => 45,
                'nombre' => 'PROCURADURÍA FISCAL',
                'acceso' => NULL,
                'ip' => '10.1.17.90',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'PROCURADURÍA FISCAL',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            59 => 
            array (
                'biometrico_id' => 46,
                'nombre' => 'RECINTO_FISCAL',
                'acceso' => NULL,
                'ip' => '10.1.202.145',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'RECINTO_FISCAL',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            60 => 
            array (
                'biometrico_id' => 47,
                'nombre' => 'RLOZA P-2',
                'acceso' => NULL,
                'ip' => '10.1.12.149',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'RLOZA P-2',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            61 => 
            array (
                'biometrico_id' => 48,
                'nombre' => 'RLOZA P-5',
                'acceso' => NULL,
                'ip' => '10.1.12.150',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'RLOZA P-5',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            62 => 
            array (
                'biometrico_id' => 49,
                'nombre' => 'RLOZA P-8',
                'acceso' => NULL,
                'ip' => '10.1.12.151',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'RLOZA P-8',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            63 => 
            array (
                'biometrico_id' => 50,
                'nombre' => 'RLOZA PB1',
                'acceso' => NULL,
                'ip' => '10.1.12.146',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'RLOZA PB1',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            64 => 
            array (
                'biometrico_id' => 51,
                'nombre' => 'RLOZA PB2',
                'acceso' => NULL,
                'ip' => '10.1.12.147',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'RLOZA PB2',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            65 => 
            array (
                'biometrico_id' => 52,
                'nombre' => 'RLOZA PB3',
                'acceso' => NULL,
                'ip' => '10.1.12.148',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'RLOZA PB3',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            66 => 
            array (
                'biometrico_id' => 53,
                'nombre' => 'SAT-ANAHUAC 38766',
                'acceso' => NULL,
                'ip' => '10.1.131.50',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'SAT-ANAHUAC 38766',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            67 => 
            array (
                'biometrico_id' => 54,
                'nombre' => 'SAT-ARAGON 38766',
                'acceso' => NULL,
                'ip' => '10.1.132.50',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'SAT-ARAGON 38766',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            68 => 
            array (
                'biometrico_id' => 55,
                'nombre' => 'SAT-CENTRO MÉDICO',
                'acceso' => NULL,
                'ip' => '10.1.134.114',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'SAT-CENTRO MÉDICO',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            69 => 
            array (
                'biometrico_id' => 56,
                'nombre' => 'SAT-CIEN METROS 38766',
                'acceso' => NULL,
                'ip' => '10.1.146.162',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'SAT-CIEN METROS 38766',
                'activo' => false,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            70 => 
            array (
                'biometrico_id' => 57,
                'nombre' => 'SAT-CORUÑA',
                'acceso' => NULL,
                'ip' => '10.1.133.178',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'SAT-CORUÑA',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            71 => 
            array (
                'biometrico_id' => 58,
                'nombre' => 'SAT-MINA',
                'acceso' => NULL,
                'ip' => '10.1.133.114',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'SAT-MINA',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            72 => 
            array (
                'biometrico_id' => 59,
                'nombre' => 'SAT-MODULO CENTRAL',
                'acceso' => NULL,
                'ip' => '10.1.17.81',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'SAT-MODULO CENTRAL',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            73 => 
            array (
                'biometrico_id' => 60,
                'nombre' => 'SAT-SAN ANTONIO',
                'acceso' => NULL,
                'ip' => '10.1.147.161',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'SAT-SAN ANTONIO',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            74 => 
            array (
                'biometrico_id' => 61,
                'nombre' => 'SAT-SAN BORJA',
                'acceso' => NULL,
                'ip' => '10.1.150.169',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'SAT-SAN BORJA',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            75 => 
            array (
                'biometrico_id' => 62,
                'nombre' => 'SAT-TECNOPARQUE 38766',
                'acceso' => NULL,
                'ip' => '10.1.132.153',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'SAT-TECNOPARQUE 38766',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
            76 => 
            array (
                'biometrico_id' => 63,
                'nombre' => 'SAT-TEPEYAC 38766',
                'acceso' => NULL,
                'ip' => '10.1.131.242',
                'tipo' => 'DACTILAR',
                'ubicacion' => 'SAT-TEPEYAC 38766',
                'activo' => true,
                'created_at' => '2024-04-19 17:59:10',
                'updated_at' => '2024-04-19 17:59:10',
            ),
        ));
        
        DB::statement("SELECT setval('p15_biometricos_biometrico_id_seq', (SELECT MAX(biometrico_id) FROM p15_biometricos));");
    }
}