<?php

namespace Database\Seeders\p15_asistencia;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class P15HorariosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('p15_horarios')->delete();
        
        \DB::table('p15_horarios')->insert(array (
            0 => 
            array (
                'horario_id' => 5,
                'entrada' => '02:00:00',
                'salida' => '08:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            1 => 
            array (
                'horario_id' => 6,
                'entrada' => '03:00:00',
                'salida' => '09:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            2 => 
            array (
                'horario_id' => 7,
                'entrada' => '03:00:00',
                'salida' => '15:00:00',
                'dias' => '1000001',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            3 => 
            array (
                'horario_id' => 8,
                'entrada' => '04:00:00',
                'salida' => '16:00:00',
                'dias' => '1000001',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            4 => 
            array (
                'horario_id' => 9,
                'entrada' => '05:00:00',
                'salida' => '17:00:00',
                'dias' => '1000001',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            5 => 
            array (
                'horario_id' => 10,
                'entrada' => '06:00:00',
                'salida' => '13:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            6 => 
            array (
                'horario_id' => 11,
                'entrada' => '06:00:00',
                'salida' => '12:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            7 => 
            array (
                'horario_id' => 12,
                'entrada' => '06:00:00',
                'salida' => '13:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            8 => 
            array (
                'horario_id' => 13,
                'entrada' => '07:00:00',
                'salida' => '14:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            9 => 
            array (
                'horario_id' => 14,
                'entrada' => '07:00:00',
                'salida' => '13:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            10 => 
            array (
                'horario_id' => 15,
                'entrada' => '07:00:00',
                'salida' => '14:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            11 => 
            array (
                'horario_id' => 16,
                'entrada' => '07:00:00',
                'salida' => '19:00:00',
                'dias' => '1000001',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            12 => 
            array (
                'horario_id' => 17,
                'entrada' => '07:00:00',
                'salida' => '15:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            13 => 
            array (
                'horario_id' => 18,
                'entrada' => '08:00:00',
                'salida' => '20:00:00',
                'dias' => '1000001',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            14 => 
            array (
                'horario_id' => 19,
                'entrada' => '08:00:00',
                'salida' => '14:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            15 => 
            array (
                'horario_id' => 20,
                'entrada' => '08:00:00',
                'salida' => '15:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            16 => 
            array (
                'horario_id' => 21,
                'entrada' => '08:00:00',
                'salida' => '15:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            17 => 
            array (
                'horario_id' => 22,
                'entrada' => '08:00:00',
                'salida' => '11:30:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            18 => 
            array (
                'horario_id' => 23,
                'entrada' => '08:00:00',
                'salida' => '14:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            19 => 
            array (
                'horario_id' => 24,
                'entrada' => '08:00:00',
                'salida' => '15:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            20 => 
            array (
                'horario_id' => 25,
                'entrada' => '08:00:00',
                'salida' => '16:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            21 => 
            array (
                'horario_id' => 26,
                'entrada' => '08:00:00',
                'salida' => '15:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            22 => 
            array (
                'horario_id' => 27,
                'entrada' => '08:00:00',
                'salida' => '20:00:00',
                'dias' => '1000001',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            23 => 
            array (
                'horario_id' => 28,
                'entrada' => '08:00:00',
                'salida' => '16:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            24 => 
            array (
                'horario_id' => 29,
                'entrada' => '09:00:00',
                'salida' => '16:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            25 => 
            array (
                'horario_id' => 30,
                'entrada' => '09:00:00',
                'salida' => '17:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            26 => 
            array (
                'horario_id' => 31,
                'entrada' => '09:00:00',
                'salida' => '18:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            27 => 
            array (
                'horario_id' => 32,
                'entrada' => '09:00:00',
                'salida' => '15:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            28 => 
            array (
                'horario_id' => 33,
                'entrada' => '09:00:00',
                'salida' => '19:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            29 => 
            array (
                'horario_id' => 34,
                'entrada' => '09:00:00',
                'salida' => '15:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            30 => 
            array (
                'horario_id' => 35,
                'entrada' => '09:00:00',
                'salida' => '18:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            31 => 
            array (
                'horario_id' => 36,
                'entrada' => '09:00:00',
                'salida' => '16:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            32 => 
            array (
                'horario_id' => 37,
                'entrada' => '09:00:00',
                'salida' => '21:00:00',
                'dias' => '1000001',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            33 => 
            array (
                'horario_id' => 38,
                'entrada' => '09:00:00',
                'salida' => '21:00:00',
                'dias' => '1000001',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            34 => 
            array (
                'horario_id' => 39,
                'entrada' => '10:00:00',
                'salida' => '17:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            35 => 
            array (
                'horario_id' => 40,
                'entrada' => '10:00:00',
                'salida' => '16:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            36 => 
            array (
                'horario_id' => 41,
                'entrada' => '10:00:00',
                'salida' => '19:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            37 => 
            array (
                'horario_id' => 42,
                'entrada' => '10:00:00',
                'salida' => '17:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            38 => 
            array (
                'horario_id' => 43,
                'entrada' => '10:00:00',
                'salida' => '18:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            39 => 
            array (
                'horario_id' => 44,
                'entrada' => '10:00:00',
                'salida' => '22:00:00',
                'dias' => '1000001',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            40 => 
            array (
                'horario_id' => 45,
                'entrada' => '10:00:00',
                'salida' => '22:00:00',
                'dias' => '1000001',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            41 => 
            array (
                'horario_id' => 46,
                'entrada' => '11:00:00',
                'salida' => '18:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            42 => 
            array (
                'horario_id' => 47,
                'entrada' => '11:00:00',
                'salida' => '19:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            43 => 
            array (
                'horario_id' => 48,
                'entrada' => '11:00:00',
                'salida' => '18:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            44 => 
            array (
                'horario_id' => 49,
                'entrada' => '11:00:00',
                'salida' => '18:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            45 => 
            array (
                'horario_id' => 50,
                'entrada' => '12:00:00',
                'salida' => '19:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            46 => 
            array (
                'horario_id' => 51,
                'entrada' => '12:00:00',
                'salida' => '19:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            47 => 
            array (
                'horario_id' => 52,
                'entrada' => '12:00:00',
                'salida' => '20:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            48 => 
            array (
                'horario_id' => 53,
                'entrada' => '12:00:00',
                'salida' => '19:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            49 => 
            array (
                'horario_id' => 54,
                'entrada' => '13:00:00',
                'salida' => '20:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            50 => 
            array (
                'horario_id' => 55,
                'entrada' => '13:00:00',
                'salida' => '21:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            51 => 
            array (
                'horario_id' => 56,
                'entrada' => '14:00:00',
                'salida' => '20:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            52 => 
            array (
                'horario_id' => 57,
                'entrada' => '14:00:00',
                'salida' => '21:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            53 => 
            array (
                'horario_id' => 58,
                'entrada' => '14:00:00',
                'salida' => '22:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:15',
                'updated_at' => '2024-04-17 14:04:15',
            ),
            54 => 
            array (
                'horario_id' => 59,
                'entrada' => '14:00:00',
                'salida' => '21:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:16',
                'updated_at' => '2024-04-17 14:04:16',
            ),
            55 => 
            array (
                'horario_id' => 60,
                'entrada' => '14:00:00',
                'salida' => '20:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:16',
                'updated_at' => '2024-04-17 14:04:16',
            ),
            56 => 
            array (
                'horario_id' => 61,
                'entrada' => '15:00:00',
                'salida' => '21:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:16',
                'updated_at' => '2024-04-17 14:04:16',
            ),
            57 => 
            array (
                'horario_id' => 62,
                'entrada' => '15:00:00',
                'salida' => '22:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:16',
                'updated_at' => '2024-04-17 14:04:16',
            ),
            58 => 
            array (
                'horario_id' => 63,
                'entrada' => '15:00:00',
                'salida' => '21:30:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:16',
                'updated_at' => '2024-04-17 14:04:16',
            ),
            59 => 
            array (
                'horario_id' => 64,
                'entrada' => '15:00:00',
                'salida' => '22:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:16',
                'updated_at' => '2024-04-17 14:04:16',
            ),
            60 => 
            array (
                'horario_id' => 65,
                'entrada' => '15:00:00',
                'salida' => '21:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:16',
                'updated_at' => '2024-04-17 14:04:16',
            ),
            61 => 
            array (
                'horario_id' => 66,
                'entrada' => '15:30:00',
                'salida' => '22:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:16',
                'updated_at' => '2024-04-17 14:04:16',
            ),
            62 => 
            array (
                'horario_id' => 67,
                'entrada' => '16:00:00',
                'salida' => '22:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:16',
                'updated_at' => '2024-04-17 14:04:16',
            ),
            63 => 
            array (
                'horario_id' => 68,
                'entrada' => '16:00:00',
                'salida' => '19:00:00',
                'dias' => '0000100',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:16',
                'updated_at' => '2024-04-17 14:04:16',
            ),
            64 => 
            array (
                'horario_id' => 69,
                'entrada' => '16:00:00',
                'salida' => '22:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:16',
                'updated_at' => '2024-04-17 14:04:16',
            ),
            65 => 
            array (
                'horario_id' => 70,
                'entrada' => '16:00:00',
                'salida' => '22:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:16',
                'updated_at' => '2024-04-17 14:04:16',
            ),
            66 => 
            array (
                'horario_id' => 71,
                'entrada' => '18:00:00',
                'salida' => '24:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:16',
                'updated_at' => '2024-04-17 14:04:16',
            ),
            67 => 
            array (
                'horario_id' => 72,
                'entrada' => '21:00:00',
                'salida' => '03:00:00',
                'dias' => '0111110',
                'es_horario_base' => false,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:04:16',
                'updated_at' => '2024-04-17 14:04:16',
            ),
            68 => 
            array (
                'horario_id' => 1,
                'entrada' => '08:00:00',
                'salida' => '15:00:00',
                'dias' => '0111110',
                'es_horario_base' => true,
                'aplica_retardos' => true,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:02:40',
                'updated_at' => '2024-04-17 14:02:40',
            ),
            69 => 
            array (
                'horario_id' => 2,
                'entrada' => '08:00:00',
                'salida' => '15:00:00',
                'dias' => '0111110',
                'es_horario_base' => true,
                'aplica_retardos' => false,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NO_SINDICALIZADO',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:02:40',
                'updated_at' => '2024-04-17 14:02:40',
            ),
            70 => 
            array (
                'horario_id' => 3,
                'entrada' => '09:00:00',
                'salida' => '19:00:00',
                'dias' => '0111110',
                'es_horario_base' => true,
                'aplica_retardos' => false,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'ESTRUCTURA',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:02:40',
                'updated_at' => '2024-04-17 14:02:40',
            ),
            71 => 
            array (
                'horario_id' => 4,
                'entrada' => '09:00:00',
                'salida' => '19:00:00',
                'dias' => '0111110',
                'es_horario_base' => true,
                'aplica_retardos' => false,
                'dias_festivos_son_laborales' => false,
                'tipo_empleado' => 'NOMINA_8',
                'tipo_asignacion' => 'SISTEMA',
                'activo' => true,
                'created_at' => '2024-04-17 14:02:40',
                'updated_at' => '2024-04-17 14:02:40',
            ),
        ));
        
        DB::statement("SELECT setval('p15_horarios_horario_id_seq', (SELECT MAX(horario_id) FROM p15_horarios));");
    }
}